services:
  app:
    build:
      context: . 
    volumes:
      - .:/usr/src/app/
    command:
      - scripts/start_app.sh
    ports:
      - "8000:8000"
    env_file:
      - app.env
      - database.env

  database:
    image: postgres:14.3
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: